# Generated by Django 4.2.13 on 2024-07-01 02:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0002_remove_usuarios_activo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuarios',
            name='rut',
            field=models.CharField(max_length=20, primary_key=True, serialize=False),
        ),
    ]
