# Generated by Django 4.2.13 on 2024-07-01 02:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0003_alter_usuarios_rut'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuarios',
            name='apellido_materno',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='usuarios',
            name='apellido_paterno',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='usuarios',
            name='fecha_nacimiento',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='usuarios',
            name='id_genero',
            field=models.ForeignKey(db_column='idGenero', null=True, on_delete=django.db.models.deletion.CASCADE, to='usuarios.genero'),
        ),
        migrations.AlterField(
            model_name='usuarios',
            name='nombre',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='usuarios',
            name='telefono',
            field=models.CharField(max_length=45, null=True),
        ),
    ]
